### PR TITLE
Add optional football crest in tag

### PR DESCRIPTION
**Pull request by AT-GDN**
First part of a small project to enable football crest assets to be setup in tag manager and retrieved by users in an optimised way. This introduces a new field to the thrift schema for the football crest image, as discussed with @currysoup and @mchv .

### CODE REVIEW

**Comment by itsibitzi** [comment]
Heya!

Is this supposed to be a new tag type? Or will we keep it as a topic tag?

**Comment by mchv** [comment]
> Is this supposed to be a new tag type? Or will we keep it as a topic tag?

we agreed to not add a new type tag

**Comment by mchv** [comment]
👍

**Review by itsibitzi — APPROVED** [review]

**Comment by AT-GDN** [comment]
Hi @currysoup , thanks for looking at this. As @mchv clarified with the updated description, this PR is supposed to add an optional 'footballCrest' to tag and not add a new tag type. Apologies for the confusion!

**Pull request merged**
