### PR TITLE
New Pillar model

### PR DESCRIPTION
**Pull request by tomrf1**
These will be created by tagmanager, and as with tags/sections it will use path-manager

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
@tomrf1 What is a Pillar?

**Comment by tomrf1** [comment]
@LATaylor-guardian good question! It's a new container, being introduced as part of the Garnett project.
It's basically just a set of sections. CAPI will return a `pillarId` as well as the `sectionId` for content.
The new styling will be based on pillars. Chris W can probably give a more complete explanation if you're interested :)

**Comment by LATaylor-guardian** [comment]
@tomrf1 Thanks. 
@chriswilk I have a couple of questions.  

1. Is this data structure for data or for driving how something looks on the Frontend? The distinction is very important. CAPI does not care how consumers of it present the data (separation of concerns).
2. How are `Pillars` created?
3. Can this be achieved with existing endpoints?
4. How does how we model our data relate to Garnett?

**Comment by tomrf1** [comment]
I'd say it's 'data' in the same way sections are data.
A piece of content has a section, and a section has a pillar.
Sections will be added to pillars from tagmanager.

**Comment by mchv** [comment]
👍

**Pull request merged**
