### PR TITLE
Add validFrom and validTo fields to Sponsorship.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**

### CODE REVIEW

**Comment by itsibitzi** [comment]
LGTM :+1: - only nitpick is if we're using semver then it should be a minor version bump not a patch 😁

**Review by itsibitzi — APPROVED** [review]

**Comment by LATaylor-guardian** [comment]
@currysoup I'll change the version quickly.

**Comment by LATaylor-guardian** [comment]
@currysoup done. Good to go.

**Review by itsibitzi — APPROVED** [review]
🚀

**Pull request merged**
